baseurl = "/"
languageCode = "en-us"
title = "A minimal Hugo website"
theme = "milano"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = -100
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = -50
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -25
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 100

[params]
    description = "A website built through Hugo."
    footer = "&copy; [YourName](https://yoururl.com) 2017 | [Github](https://github.com/oneleaftea) | [Twitter](https://twitter.com/xieyihui)"
